lms2 = dsp.LMSFilter('Length',11, ...
   'Method','Normalized LMS',...
   'AdaptInputPort',true, ...
   'StepSizeSource','Input port', ...
   'WeightsOutputPort',false);
x = 0; % Fill with input signal
d = 0; % d to 0 tentatively
a = 1; % adaptation control
mu = 0.05; % step size
[y, err] = step(lms2,x,d,mu,a)
