lms2 = dsp.LMSFilter('Length',11, ...
   'Method','Normalized LMS',...
   'AdaptInputPort',true, ...
   'StepSizeSource','Input port', ...
   'WeightsOutputPort',false);
x = ; % Noise spectrum
d = x; % Set error to zero
a = 1; % adaptation control
mu = 0.05; % step size
[y, err] = step(lms2,x,d,mu,a); % Take error microphone as 0